### ISSUE TITLE
 Extend API for get active focus or when Clause Contexts

### ISSUE THREAD

**Issue by LexiconCode** [mkloubert/vs-rest-api#1]
I'm working on a project that could benefit from VS rest api. I'm working with a voice to text control VS. Currently I don't see a method to call the active focus VS or 'when Clause Contexts'. A [use case](https://stackoverflow.com/questions/43372232/a-method-to-expose-the-vscode-active-when-clause-contexts) example.

Your thoughts would be appreciated.

**Comment by mkloubert** [comment]
@LexiconCode 

Is that right?: The framework processes speech and invokes code, you have defined in inside the framework.

If so: You can define [custom endpoints](https://github.com/mkloubert/vs-rest-api/wiki#custom-endpoints-) and use the [vscode API](https://code.visualstudio.com/docs/extensionAPI/vscode-api) to control the editor, like executing commands or handling editor events, by [Node.js](https://nodejs.org/) based scripts.
The framework can do the calls to that custom endpoints and invoke the logic, you have defined in the scripts.

**Comment by LexiconCode** [comment]
@mkloubert 

Correct, Dragonfly usage is to create a static voice command with a callback that will be called when the command is spoken. Your API saves me a tremendous amount of work. It allows me the freedom to develop and test the implementation on Dragonfly without crating my own API first. This is the first step of a larger goal as teach myself programming with the tools by voice. So thank you for your thoughtful reply.

My goal is to create an API between dragonfly and other applications. Eventually the API server would be Independent from VS separate from the vs extension.. The VS extension would then become a client. That's a little ways off. :)
